// استيراد نوع Metadata لتحديد بيانات الموقع
// مثل عنوان الصفحة والوصف الذي يظهر في محركات البحث
import type { Metadata } from "next";

// استيراد خطوط Geist من مكتبة خطوط Next.js
import { Geist, Geist_Mono } from "next/font/google";

// استيراد ملف الـ CSS العام الخاص بالمشروع
import "./globals.css";


// إنشاء إعدادات خط Geist العادي
const geistSans = Geist({
  // حفظ اسم الخط داخل CSS Variable
  variable: "--font-geist-sans",

  // تحديد مجموعة الحروف المستخدمة
  subsets: ["latin"],
});


// إنشاء إعدادات خط Geist Mono
// وهو خط مناسب غالبًا لعرض الأكواد
const geistMono = Geist_Mono({
  // حفظ اسم الخط داخل CSS Variable
  variable: "--font-geist-mono",

  // تحديد مجموعة الحروف المستخدمة
  subsets: ["latin"],
});


// بيانات الموقع أو الصفحة
// Next.js تستخدمها تلقائيًا داخل الـ <head>
export const metadata: Metadata = {
  // عنوان الموقع الذي يظهر في الـ Browser Tab
  title: "Create Next App",

  // وصف الموقع لمحركات البحث
  description: "Generated by create next app",
};


// RootLayout هو الـ Layout الرئيسي للمشروع
// وكل الصفحات والمكونات تظهر داخل children
export default function RootLayout({
  children,
}: Readonly<{
  // children تمثل محتوى الصفحات
  // مثل الصفحة الرئيسية أو أي صفحة أخرى
  children: React.ReactNode;
}>) {
  return (
    // العنصر الرئيسي للـ HTML
    <html
      // تحديد لغة الموقع بالإنجليزية
      lang="en"

      // إضافة خطوط Geist
      // h-full تجعل ارتفاع الصفحة 100%
      // antialiased تحسن شكل ونعومة الخطوط
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* جسم الموقع الذي يحتوي على كل المحتوى */}
      <body
        // min-h-full تجعل أقل ارتفاع للصفحة 100%
        // flex flex-col تجعل العناصر مرتبة رأسيًا
        className="min-h-full flex flex-col"
      >
        {/* عرض محتوى الصفحات داخل الـ Layout */}
        {children}
      </body>
    </html>
  );
}